export const Constants = {
    USERNAME: "JEK_USERNAME",
    TOKEN: "JEK_TOKEN",
    USER_ROLE:"ROLE",
    TOKEN_KEY:"AuthToken",
    REETRAK_USER: 'Administrator',
    REETRAK_ADMIN:'Admin',
  
    ROLE_ADMIN:"1",
    ROLE_USER:"2",
  
  
  
    EDIT: 'EDIT',
    ADD: 'ADD',
    VIEW: 'VIEW',
    FLG_ENABLE: 1,
    TNT: 'TNT',
    BPO: 'BPO',
    BIS: 'BIS',
    TIS: 'TIS',
    TNT_TYPE: 1,
    BPO_TYPE: 2,
    BIS_TYPE: 3,
    TIS_TYPE: 4,
  
    NOT_REQUIRED:"Not Required",
    REQUIRED:"Required",
  
  
  
  
  //MODULEAPP
  WD:"WD",
  GA:"GA",
  DQ:"DQ",
  NFS:"NFS",
  
  
  // Lov Config
  LOV_LOVNAME: "Name",
  LOV_DESCR: "Description",
  LOV_ACTIVE: "LOV_ACTIVE",
  LOV_NAME: "Name",
  LOV_VALUE: "Value",
  
  
  COMMON_RESET_ICON: "autorenew",
  COMMON_ACTIVE_ICON: "done",
  COMMON_DEACTIVE_ICON: "block",
  COMMON_EDIT_ICON: "edit",
  COMMON_ADD_ICON: "add",
  COMMON_INFO_ICON: "info",
  COMMON_REFRESH_ICON: "refresh",
  NEW: "NEW",
  
  APP_ACTIVE: true,
  
  NAME:"name",
  DESCRIPTION:"description",
  
  /* Customer Atribute*/
  PROJECT_TYPE:"PROJECT_TYPE",
  SHIPMENT_TYPE:"SHIPMENT_TYPE",
  /* Line Atribute*/
  LINE_TYPE:"LINE_TYPE",
  PACKAGING_TYPE:"PACKAGING_TYPE",
  /* Machine Attributes*/
  MACHINE_TYPE:"MACHINE_TYPE",
  MACHINE_MAKE:"MACHINE_MAKE",
  MACHINE_SPEED:"MACHINE_SPEED",
  MACHINE_GRADING:"GRADING",
  MACHINE_PRINTER:"PRINTER",
  MACHINE_INSPECTION:"INSPECTION",
  MACHINE_REJECTION:"REJECTION",
  MACHINE_SHRINK:"SHRINK",
  MACHINE_SCANNER:"SCANNER",
  MACHINE_SMART_CAMERA:"SMART CAMERA",
  MACHINE_LICENSE:"LICENCE",
  MACHINE_POWER_REQUIREMENT:"POWER REQUIREMENT",
  MACHINE_HARDWARE_SPEC:"MACHINE_HARDWARE_SPEC",
  MACHINE_MONITOR:"MONITOR",
  MACHINE_SCANNING_CAPABLITIES:"SCANNING CAPABILITIES",
  MACHINE_BOTTLE_TYPE:"BOTTLE TYPE",
  MACHINE_LABEL_SIZE:"LABEL SIZE",
  MACHINE_PRINTLAYOUT_SAMPLE:"PRINT LAYOUT SAMPLE",
  MACHINE_PACKAGING_TYPE:"PACKAGING_TYPE",
  }
  